// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection; Supabase's pooled
    // port 6543 (pgbouncer) doesn't support the transactions migrate needs.
    url: process.env["DIRECT_URL"],
  },
});
